### ISSUE TITLE
Feature request: add option to sequentially arrange guides in Collections

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/chronos-frontend#35]
Currently, the articles in the [Docs collection](https://documentation.vanillaos.org/collections/docs) are randomly arranged, this would confuse new users on what to read first. So I would suggest adding an option to specify the sequence/order of pages that docs team members can curate for a better beginner-friendly experience for specific collections.

**Comment by muhdsalm** [comment]
Now that we have support for stories, is this still necessary?
