### ISSUE TITLE
Bug: fix support for auto dark/light mode switching

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/chronos-frontend#84]

**Comment by mirkobrombin** [comment]
Pinging @GabsEdits since he made some changes recently

**Comment by GabsEdits** [comment]
Wasn't this fixed in https://github.com/Vanilla-OS/chronos-frontend/commit/a7546b2e81ec30f1975c9f349e1be6dc72d8b26b ? It seems fine for me

**Comment by kbdharun** [comment]
> Update: I just checked, you need clear the cache. Once you do that everything should work well, as it did for me

Yep, can confirm the same, would it be possible to seamlessly achieve the same without requiring clearing of cache or force reloading the page?

**Comment by GabsEdits** [comment]
> > Update: I just checked, you need clear the cache. Once you do that everything should work well, as it did for me
> 
> Yep, can confirm the same, would it be possible to seamlessly achieve the same without requiring clearing of cache or force reloading the page?

The requirement of clearing of cache is here just because this was a recent change. I believe it's possible to make new option that follows always the system setting, something like what [Docus](https://docus.dev/) does. I can investigate it if you want.

**Comment by kbdharun** [comment]
> The requirement of clearing of cache is here just because this was a recent change. I believe it's possible to make new option that follows always the system setting, something like what [Docus](https://docus.dev/) does. I can investigate it if you want.

Sure, feel free to investigate it and let me know if you find something.
